# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Check existence of Cinny systemd service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ cinny_identifier }}.service"
  register: cinny_service_stat

- name: Uninstall Cinny systemd services and files
  when: cinny_service_stat.stat.exists | bool
  block:
    - name: Ensure Cinny systemd service is stopped
      ansible.builtin.service:
        name: "{{ cinny_identifier }}"
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Ensure Cinny systemd service does not exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/{{ cinny_identifier }}.service"
        state: absent

    - name: Ensure Cinny container network does not exist via community.docker.docker_network
      when: devture_systemd_docker_base_container_network_creation_method == 'ansible-module'
      community.docker.docker_network:
        name: "{{ cinny_container_network }}"
        state: absent

    - name: Ensure Cinny container network does not exist via ansible.builtin.command
      when: devture_systemd_docker_base_container_network_creation_method == 'command'
      ansible.builtin.command:
        cmd: >-
          {{ devture_systemd_docker_base_host_command_docker }} network rm
          {{ cinny_container_network }}
      register: network_deletion_result
      changed_when: cinny_container_network in network_deletion_result.stdout

    - name: Ensure Cinny path does not exist
      ansible.builtin.file:
        path: "{{ cinny_base_path }}"
        state: absent
