# SPDX-FileCopyrightText: 2023 Julian-Samuel GebÃ¼hr
# SPDX-FileCopyrightText: 2023 MASH project contributors
# SPDX-FileCopyrightText: 2023-2025 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Fail if required Hydrogen settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item }}`).
  when: "item.when | bool and lookup('vars', item.name, default='') | string | length == 0"
  with_items:
    - { "name": "hydrogen_uid", when: true }
    - { "name": "hydrogen_gid", when: true }
    - { "name": "hydrogen_hostname", when: true }
    - { "name": "hydrogen_path_prefix", when: true }
    - { "name": "hydrogen_container_network", when: true }
    - { "name": "hydrogen_default_hs_url", when: true }
    - { "name": "hydrogen_container_labels_traefik_compression_middleware_name", when: "{{ hydrogen_container_labels_traefik_compression_middleware_enabled }}" }

- name: Run if Traefik is enabled
  when: hydrogen_container_labels_traefik_enabled | bool
  block:
    - name: Fail if Traefik settings required for Hydrogen are not defined
      ansible.builtin.fail:
        msg: >-
          You need to define a required configuration setting (`{{ item }}`).
      when: "lookup('vars', item, default='') | string | length == 0"
      with_items:
        - hydrogen_container_labels_traefik_hostname
        - hydrogen_container_labels_traefik_path_prefix

    # We ensure it doesn't end with a slash, because we handle both (slash and no-slash).
    # Knowing that `hydrogen_container_labels_traefik_path_prefix` does not end with a slash
    # ensures we know how to set these routes up without having to do "does it end with a slash" checks elsewhere.
    - name: Fail if hydrogen_container_labels_traefik_path_prefix ends with a slash
      ansible.builtin.fail:
        msg: >-
          hydrogen_container_labels_traefik_path_prefix (`{{ hydrogen_container_labels_traefik_path_prefix }}`) must either be `/` or not end with a slash (e.g. `/hydrogen`).
      when: "hydrogen_container_labels_traefik_path_prefix != '/' and hydrogen_container_labels_traefik_path_prefix[-1] == '/'"
